chore: de-zarfify maru-runner
defenseunicorns/maru-runner pull request #73
Opened 2024-05-08 22:26 UTC by Racer159

## Description

This PR removes Zarf as a dependency of Maru.

## Related Issue

Fixes #23 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/maru-runner/blob/main/CONTRIBUTING.md) followed

2024-05-08 22:28 UTC, Racer159 commented
still wip, there is some breakage with files and this still depends on `message`

2024-05-15 16:49 UTC, UncleGedd commented
Re: new deps. Looking at [defenseunicorns/pkg](https://github.com/defenseunicorns/pkg), and I see `helpers` but not `exec` or `variables` . Where are these deps coming from?

2024-05-15 16:57 UTC, UncleGedd commented
I understand the registration system and removal of `config.CmdPrefix`, but I don't get the second breaking change: "Not reaching into os.Env within library code". Can we get more context there?

2024-05-15 17:30 UTC, Racer159 commented
> I understand the registration system and removal of `config.CmdPrefix`, but I don't get the second breaking change: "Not reaching into os.Env within library code". Can we get more context there?

This is a breakage for any users of Maru as a library - (which @ericwyles pointed out I was misinformed about `uds-cli`'s integration of Maru) - basically we only pull the `os.Env` in the `cmd` package now so if you use `Run` directly you'd have to inject those env vars as set variables yourself.

We should discuss but I also think that `uds-cli` should switch from vendoring Maru to calling `Run` so that it can have more control and we don't need to have global `config` vars for all of the configuration.

2024-05-15 17:53 UTC, UncleGedd commented
> We should discuss but I also think that `uds-cli` should switch from vendoring Maru to calling `Run` so that it can have more control and we don't need to have global `config` vars for all of the configuration.

👍 I'm good with that

2024-05-16 20:00 UTC, Racer159 commented
> > We should discuss but I also think that `uds-cli` should switch from vendoring Maru to calling `Run` so that it can have more control and we don't need to have global `config` vars for all of the configuration.
> 
> 👍 I'm good with that

After discussing with @ericwyles yesterday I have changed my opinion back - we could do things to make it easier to run from library code (i.e. centralizing command flags) but they likely aren't necessary near term for what UDS CLI actually needs (likely a config var thing would work and we still should be able to control it well enough that vendoring apps like zarf / uds-cli don't step on each other in the globals)

2024-05-17 18:31 UTC, ericwyles requested changes

2024-05-20 14:32 UTC, Racer159 commented
Thinking of leaving prompt in for now (as dead code we can either cleanup or implement later) - I implemented generics though for the Zarf specific variable values that are carried through.

2024-05-20 14:44 UTC, Racer159 commented on src/pkg/runner/actions.go
> +		// Remove # from env variable name.
Plan is to just have them set these as extra variables for now - we can work with Zarf to improve this in the future.

2024-05-20 14:44 UTC, Racer159 commented on src/cmd/root.go
> +	exec.RegisterCmdMutation("uds", "uds")
done

2024-05-21 20:46 UTC, ericwyles approved these changes

2024-05-22 15:18 UTC, merged